export const MODELS = [
  { name: "Claude Opus 4.7",   color: "#8b5cf6" },
  { name: "Claude Sonnet 4.6", color: "#6366f1" },
  { name: "Claude Opus 4.6",   color: "#7c3aed" },
  { name: "Claude Sonnet 4.5", color: "#a855f7" },
  { name: "Claude Opus 4.5",   color: "#c084fc" },
  { name: "Claude 3.5",        color: "#4f46e5" },
  { name: "GPT-5.5",           color: "#10b981" },
  { name: "GPT-5.4",           color: "#059669" },
  { name: "GPT-4o",            color: "#34d399" },
  { name: "GPT-4",             color: "#047857" },
  { name: "Gemini 3.1",        color: "#f59e0b" },
  { name: "Gemini 3.0",        color: "#f97316" },
  { name: "Gemini 2.0",        color: "#fb923c" },
  { name: "Llama 4",           color: "#38bdf8" },
  { name: "Llama 3",           color: "#0ea5e9" },
  { name: "Grok 4",            color: "#ef4444" },
  { name: "Qwen3",             color: "#06b6d4" },
  { name: "Qwen3-235B",        color: "#0891b2" },
  { name: "DeepSeek V3",       color: "#a78bfa" },
  { name: "DeepSeek R1",       color: "#9333ea" },
  { name: "GLM-4.5",           color: "#22c55e" },
  { name: "Kimi K2",           color: "#14b8a6" },
  { name: "MiniMax M1",        color: "#ec4899" },
  { name: "ERNIE 4.5",         color: "#3b82f6" },
  { name: "Yi-Large",          color: "#eab308" },
  { name: "Mistral",           color: "#fb7185" },
  { name: "Other",             color: "#a1a1aa" },
];

export const CATEGORIES = [
  { name: "Coding", icon: "💻" },
  { name: "Writing", icon: "✍️" },
  { name: "Science", icon: "🔬" },
  { name: "Math", icon: "📐" },
  { name: "Legal", icon: "⚖️" },
  { name: "Medical", icon: "🏥" },
  { name: "History", icon: "📜" },
  { name: "Finance", icon: "💰" },
  { name: "General", icon: "💬" },
];

export const MOCK_ANSWERS = [
  {
    id: "1",
    prompt: "How do I center a div in CSS?",
    answer:
      "The cleanest modern way is usually Flexbox: set the parent to `display: flex`, then use `justify-content: center` and `align-items: center`. If you only need horizontal centering for a fixed-width block, `margin: 0 auto` also works.",
    model: "GPT-4o",
    modelColor: "#10b981",
    category: "Coding",
    tags: ["css", "frontend", "layout", "html"],
    upvotes: 612,
    views: 12600,
    contributor: "alex_dev",
    date: "2026-04-22",
  },
  {
    id: "2",
    prompt: "How do I write a professional email asking for an update?",
    answer:
      "Keep it short, polite, and easy to answer. A good structure is: greeting, one-line reminder of the topic, polite request for an update, and a close like 'Please let me know if you need anything else from me.'",
    model: "GPT-4o",
    modelColor: "#10b981",
    category: "Writing",
    tags: ["email", "communication", "professional-writing", "follow-up"],
    upvotes: 534,
    views: 11100,
    contributor: "careercoach",
    date: "2026-04-22",
  },
  {
    id: "3",
    prompt: "Why is the sky blue?",
    answer:
      "The sky looks blue because the atmosphere scatters blue light more strongly than other visible colors. This effect is called Rayleigh scattering. At sunset, light travels through more atmosphere, so more blue light scatters away and the sky looks red or orange instead.",
    model: "Gemini 3.0",
    modelColor: "#f97316",
    category: "Science",
    tags: ["science", "light", "atmosphere", "physics"],
    upvotes: 566,
    views: 11700,
    contributor: "sciencefan",
    date: "2026-04-22",
  },
  {
    id: "4",
    prompt: "What is compound interest and how does it work?",
    answer:
      "Compound interest means you earn interest on both your original money and the interest already added. That is why growth speeds up over time. The earlier you start, the more powerful compounding becomes.",
    model: "GPT-4o",
    modelColor: "#10b981",
    category: "Math",
    tags: ["compound-interest", "math", "finance", "basics"],
    upvotes: 644,
    views: 13500,
    contributor: "financegeek",
    date: "2026-04-22",
  },
  {
    id: "5",
    prompt: "What is the difference between a virus and a bacterium?",
    answer:
      "A bacterium is a living single-celled organism. A virus is much smaller and cannot reproduce on its own. Antibiotics can work against some bacteria, but they do not work against viruses.",
    model: "GPT-4o",
    modelColor: "#10b981",
    category: "Medical",
    tags: ["virus", "bacteria", "infection", "health"],
    upvotes: 493,
    views: 9200,
    contributor: "medstudent",
    date: "2026-04-22",
  },
  {
    id: "6",
    prompt: "How do I make a simple budget?",
    answer:
      "Start by listing income, fixed costs, variable costs, and savings goals. A simple rule is 50/30/20: 50% for needs, 30% for wants, and 20% for savings or debt repayment. The goal is clarity, not perfection.",
    model: "GPT-4o",
    modelColor: "#10b981",
    category: "Finance",
    tags: ["budgeting", "money", "personal-finance", "saving"],
    upvotes: 607,
    views: 12100,
    contributor: "financegeek",
    date: "2026-04-22",
  },
];
