export const CATEGORIES = [
  { name: "Coding", icon: "💻" },
  { name: "Writing", icon: "✍️" },
  { name: "Science", icon: "🔬" },
  { name: "Math", icon: "📐" },
  { name: "Legal", icon: "⚖️" },
  { name: "Medical", icon: "🏥" },
  { name: "History", icon: "📜" },
  { name: "Finance", icon: "💰" },
  { name: "General", icon: "💬" },
];

export const MOCK_ANSWERS = [
  {
    id: "1",
    prompt: "Explain recursion in Python with a simple example",
    answer:
      "Recursion is when a function calls itself to solve smaller instances of the same problem. Here's a classic example with factorial:\n\n```python\ndef factorial(n):\n    if n <= 1:  # base case\n        return 1\n    return n * factorial(n - 1)  # recursive call\n\nprint(factorial(5))  # Output: 120\n```\n\nEvery recursive function needs: 1) A **base case** (to stop), and 2) A **recursive case** (to reduce the problem). Without a base case, you get infinite recursion and a stack overflow.",
    model: "GPT-4o",
    modelColor: "#10b981",
    category: "Coding",
    tags: ["python", "recursion", "functions"],
    upvotes: 342,
    views: 4821,
    contributor: "alex_dev",
    date: "2026-04-12",
  },
  {
    id: "2",
    prompt: "What is the difference between TCP and UDP?",
    answer:
      "**TCP (Transmission Control Protocol)** is connection-oriented , it establishes a connection before sending data, guarantees delivery, order, and error-checking. Great for: web browsing, email, file transfers.\n\n**UDP (User Datagram Protocol)** is connectionless , it fires packets without confirming receipt. Faster but unreliable. Great for: video streaming, online gaming, DNS lookups.\n\nSimple analogy: TCP is a certified letter (you know it arrived). UDP is a flyer thrown into a crowd (some might catch it, some won't).",
    model: "Claude 3.5",
    modelColor: "#818cf8",
    category: "Coding",
    tags: ["networking", "tcp", "udp", "protocols"],
    upvotes: 218,
    views: 3102,
    contributor: "netguru",
    date: "2026-04-14",
  },
  {
    id: "3",
    prompt: "Write a cover letter opening paragraph for a software engineer role at a startup",
    answer:
      "I'm a software engineer with 4 years of experience building scalable web applications, and I'm genuinely excited about [Company]'s mission to [X]. What draws me to early-stage companies is the opportunity to wear multiple hats , I thrive when I can move fast, make architectural decisions, and see my code directly impact users. At my last role, I shipped [specific achievement], and I'd love to bring that same drive to your team.",
    model: "Claude 3.7",
    modelColor: "#818cf8",
    category: "Writing",
    tags: ["cover-letter", "job-search", "startup"],
    upvotes: 156,
    views: 2890,
    contributor: "careercoach",
    date: "2026-04-15",
  },
  {
    id: "4",
    prompt: "What causes the northern lights (aurora borealis)?",
    answer:
      "The aurora borealis is caused by charged particles (mainly electrons and protons) from the Sun colliding with gas molecules in Earth's atmosphere.\n\nHere's the chain: The Sun emits a stream of particles called the **solar wind**. Earth's magnetic field deflects most of them, but near the poles the field lines converge and funnel particles down into the upper atmosphere (~100–300 km up). When these particles collide with oxygen and nitrogen, they excite the atoms, which release energy as light. Different gases produce different colors: oxygen at ~60 miles → green; oxygen at ~200 miles → red; nitrogen → blue/purple.",
    model: "Gemini 1.5",
    modelColor: "#f59e0b",
    category: "Science",
    tags: ["aurora", "solar-wind", "atmosphere", "physics"],
    upvotes: 487,
    views: 7203,
    contributor: "sciencefan",
    date: "2026-04-10",
  },
  {
    id: "5",
    prompt: "What is compound interest and how is it calculated?",
    answer:
      "Compound interest is interest calculated on both the **initial principal** and the **accumulated interest** from previous periods.\n\nFormula: **A = P(1 + r/n)^(nt)**\n\nWhere:\n- A = final amount\n- P = principal (initial investment)\n- r = annual interest rate (decimal)\n- n = times interest compounds per year\n- t = time in years\n\nExample: $1,000 at 5% compounded annually for 10 years:\nA = 1000(1 + 0.05/1)^(1×10) = **$1,628.89**\n\nVs simple interest: 1000 × (1 + 0.05 × 10) = $1,500. Compound gives you $128.89 more , and the gap grows exponentially over time.",
    model: "GPT-4o",
    modelColor: "#10b981",
    category: "Finance",
    tags: ["finance", "investing", "compound-interest", "math"],
    upvotes: 293,
    views: 5411,
    contributor: "financegeek",
    date: "2026-04-11",
  },
  {
    id: "6",
    prompt: "How does the immune system recognize pathogens?",
    answer:
      "The immune system uses a two-layer recognition system:\n\n**1. Innate immunity (fast, non-specific):** Pattern Recognition Receptors (PRRs) , especially Toll-like receptors on immune cells , detect conserved molecular patterns called PAMPs (Pathogen-Associated Molecular Patterns) shared by many pathogens (e.g., bacterial cell wall components, viral RNA). This triggers immediate inflammation.\n\n**2. Adaptive immunity (slow, specific):** Antigens (unique surface proteins) from the pathogen are presented by dendritic cells to T and B lymphocytes via MHC molecules. B cells produce antibodies that bind specifically to those antigens. Memory cells are then retained for faster future responses , this is the basis of vaccines.",
    model: "Claude 3.7",
    modelColor: "#818cf8",
    category: "Medical",
    tags: ["immune-system", "biology", "pathogens", "antibodies"],
    upvotes: 374,
    views: 6089,
    contributor: "medstudent",
    date: "2026-04-09",
  },
];
