export type Gpt55SimpleAnswer = {
  prompt: string;
  answer: string;
  category: string;
  tags: string[];
  user: string;
};

function chatGptStyleAnswer(prompt: string, summary: string, category: string) {
  const categoryDetails: Record<string, string[]> = {
    Science: [
      "The important idea is to separate the simple fact from the mechanism behind it.",
      "In science, the short answer is useful, but the explanation usually matters more because it tells you why the answer is true.",
      "A good way to think about it is to ask what forces, materials, living systems, or environmental conditions are involved.",
      "There is also usually a scale issue: some answers depend on whether we are talking about seconds, years, ecosystems, planets, or microscopic processes.",
      "That is why two answers can both sound correct but refer to slightly different situations.",
      "The practical takeaway is to remember the main cause first, then add the details only when needed.",
    ],
    Medical: [
      "For health questions, the safest answer is usually general information, not a diagnosis.",
      "The body is a system, so one habit or symptom often connects to sleep, hydration, stress, nutrition, movement, and recovery.",
      "If the question is about prevention, the most useful approach is usually consistency rather than one dramatic change.",
      "If symptoms are severe, unusual, sudden, or persistent, it is better to ask a qualified medical professional.",
      "This is especially important for children, pregnancy, chronic illness, medication interactions, or anything involving chest pain, breathing problems, fainting, or severe pain.",
      "The practical takeaway is to understand the general principle, then apply it carefully to your own situation.",
    ],
    Finance: [
      "For money questions, the key is to understand the concept before making decisions with real money.",
      "A simple financial idea can have different consequences depending on income, debt, time horizon, taxes, risk tolerance, and local rules.",
      "A useful way to apply it is to write the numbers down instead of keeping them vague in your head.",
      "Small differences can compound over time, especially with saving, debt, investing, interest rates, and fees.",
      "This is general education, not personal financial advice.",
      "The practical takeaway is to use the concept to make clearer decisions, then adapt it to your own budget and goals.",
    ],
    Writing: [
      "For writing and communication, the goal is not to sound complicated; the goal is to make the reader understand quickly.",
      "A strong answer usually has a clear purpose, a simple structure, and wording that matches the situation.",
      "Before writing, decide what the reader needs to know, what action you want from them, and what tone is appropriate.",
      "The best version is usually shorter than the first draft, because editing removes repetition and unclear phrasing.",
      "A useful test is to ask whether someone could understand the message in one quick read.",
      "The practical takeaway is to write plainly, organize the message, and make the next step obvious.",
    ],
    Math: [
      "For math questions, the most important thing is to understand the rule and then apply it step by step.",
      "Do not try to memorize only the final answer; learn the operation that gets you there.",
      "A good method is to write the known values, identify what you are trying to find, and then choose the formula or operation.",
      "Checking your result matters because simple mistakes often come from units, signs, decimals, or using the wrong total.",
      "If the result feels unrealistic, go back and estimate roughly to see whether the answer makes sense.",
      "The practical takeaway is to slow down, keep the work visible, and verify the result.",
    ],
    History: [
      "For history questions, the short answer is only the starting point.",
      "Most historical events happened because several causes built up over time, not because of one isolated moment.",
      "It helps to separate immediate triggers from deeper causes such as economics, politics, social tensions, technology, religion, geography, or ideology.",
      "The impact also matters: an event can change laws, borders, culture, trade, military power, or the way people understand society.",
      "Historical explanations are strongest when they include both context and consequence.",
      "The practical takeaway is to remember the main event, the causes behind it, and why it still matters.",
    ],
    Legal: [
      "For legal questions, the safest answer is general information because laws vary by country, state, and contract terms.",
      "The exact answer can change depending on jurisdiction, written evidence, deadlines, signatures, consumer rules, employment rules, or local procedures.",
      "A practical first step is usually to keep records: emails, photos, contracts, invoices, dates, names, and written confirmations.",
      "If money, housing, employment, immigration, court deadlines, or serious liability is involved, it is worth getting professional legal advice.",
      "Do not rely on a general explanation as a substitute for a lawyer reviewing your specific situation.",
      "The practical takeaway is to understand the concept, document everything, and check the local rules before acting.",
    ],
    General: [
      "For practical life questions, the best answer is usually simple, but not vague.",
      "A useful method is to turn the idea into a small action you can do today.",
      "Big improvements usually come from repeating a realistic habit, not from one perfect plan.",
      "It also helps to remove friction: make the good action easier and the distracting action harder.",
      "If something is not working, change the environment or the process before blaming motivation.",
      "The practical takeaway is to start small, measure what happens, and adjust instead of waiting for perfect conditions.",
    ],
  };

  const details = categoryDetails[category] ?? categoryDetails.General;

  return [
    `Short answer: ${summary}`,
    "",
    "A fuller explanation:",
    `When someone asks "${prompt}", they usually want more than a one-sentence definition. They want the direct answer, the reason behind it, and a simple way to remember it.`,
    "",
    ...details,
    "",
    "Simple example:",
    `Imagine explaining it to someone who has heard the phrase before but never really understood it. You would start with the main answer, then add one concrete example, then explain why that example proves the point.`,
    "",
    "Common mistake:",
    "The common mistake is stopping at the short answer. That can be technically correct, but it often leaves out the context that makes the answer useful.",
    "",
    "How to remember it:",
    "Keep the core idea in one sentence, then attach one example to it. The example makes the answer easier to recall later.",
    "",
    "Bottom line:",
    `${summary} The deeper value is understanding why that answer makes sense and how to apply it in a real situation.`,
  ].join("\n");
}

const GPT55_SIMPLE_ANSWER_SUMMARIES: Gpt55SimpleAnswer[] = [
  {
    prompt: "What is the longest-living tree?",
    answer: "The longest-living individual trees are usually bristlecone pines. Some are more than 4,800 years old. There are older clonal tree colonies, but for a single tree, bristlecone pine is the best-known example.",
    category: "Science",
    tags: ["nature", "trees", "records", "science"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is the fastest animal in the world?",
    answer: "The fastest animal is the peregrine falcon when it dives, reaching more than 300 km/h. On land, the cheetah is the fastest, reaching around 100 km/h for short bursts.",
    category: "Science",
    tags: ["animals", "records", "nature"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why is the ocean salty?",
    answer: "The ocean is salty because rainwater dissolves minerals from rocks, and rivers carry those salts into the sea. Water evaporates, but the salts stay behind and build up over time.",
    category: "Science",
    tags: ["ocean", "water", "science", "nature"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why is the sky blue?",
    answer: "The sky is blue because Earth's atmosphere scatters blue light more strongly than other visible colors. This is called Rayleigh scattering.",
    category: "Science",
    tags: ["sky", "light", "physics"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why do leaves change color in autumn?",
    answer: "Leaves change color because trees produce less chlorophyll as days get shorter. As the green fades, yellow, orange, and red pigments become easier to see.",
    category: "Science",
    tags: ["trees", "autumn", "nature"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is the closest planet to the Sun?",
    answer: "Mercury is the closest planet to the Sun. It is small, rocky, and completes one orbit around the Sun in only 88 Earth days.",
    category: "Science",
    tags: ["space", "planets", "astronomy"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "How many planets are in the solar system?",
    answer: "There are 8 planets in the solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. Pluto is classified as a dwarf planet.",
    category: "Science",
    tags: ["space", "planets", "astronomy"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why does the Moon shine at night?",
    answer: "The Moon does not make its own light. It shines because it reflects sunlight. Its shape appears to change because of its position relative to Earth and the Sun.",
    category: "Science",
    tags: ["moon", "space", "astronomy"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why do cats purr?",
    answer: "Cats often purr when they are relaxed, but they can also purr when stressed, injured, or seeking comfort. Purring is a way to communicate and self-soothe.",
    category: "Science",
    tags: ["cats", "animals", "behavior"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why do dogs wag their tails?",
    answer: "Dogs wag their tails to communicate emotions such as excitement, curiosity, friendliness, or stress. The rest of the dog's body language gives the full meaning.",
    category: "Science",
    tags: ["dogs", "animals", "behavior"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is the largest animal in the world?",
    answer: "The largest animal in the world is the blue whale. It can grow longer than 25 meters and weigh more than 100 tons.",
    category: "Science",
    tags: ["animals", "whales", "records"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is the largest ocean in the world?",
    answer: "The Pacific Ocean is the largest ocean in the world. It covers about one-third of Earth's surface.",
    category: "Science",
    tags: ["ocean", "geography", "earth"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why can airplanes fly?",
    answer: "Airplanes fly because their wings create lift. The engines provide speed, and the wing shape helps push air in a way that creates an upward force.",
    category: "Science",
    tags: ["airplanes", "physics", "transport"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why is fire hot?",
    answer: "Fire is hot because combustion releases energy. That energy appears as heat and light.",
    category: "Science",
    tags: ["fire", "chemistry", "energy"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why does ice float on water?",
    answer: "Ice floats because it is less dense than liquid water. When water freezes, its molecules form a more open structure that takes up more space.",
    category: "Science",
    tags: ["water", "ice", "physics"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why do seasons exist?",
    answer: "Seasons exist because Earth's axis is tilted. During the year, different parts of Earth receive different amounts of direct sunlight.",
    category: "Science",
    tags: ["seasons", "earth", "astronomy"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why does it rain?",
    answer: "It rains when water vapor forms clouds, condenses into droplets, and the droplets become heavy enough to fall from the sky.",
    category: "Science",
    tags: ["rain", "weather", "water"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why do rainbows appear?",
    answer: "Rainbows appear when sunlight passes through water droplets. The light bends, reflects, and separates into different colors.",
    category: "Science",
    tags: ["rainbow", "light", "weather"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why do magnets attract metal?",
    answer: "Magnets attract some metals because they create a magnetic field. Metals such as iron, nickel, and cobalt respond strongly to that field.",
    category: "Science",
    tags: ["magnets", "magnetism", "physics"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is the lightest metal?",
    answer: "Lithium is the lightest metal. It is very reactive and is commonly used in rechargeable batteries.",
    category: "Science",
    tags: ["metals", "chemistry", "lithium"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is the difference between a star and a planet?",
    answer: "A star produces its own light through nuclear reactions. A planet does not make its own light; it reflects light from a star and orbits around it.",
    category: "Science",
    tags: ["stars", "planets", "astronomy"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why did dinosaurs go extinct?",
    answer: "The leading explanation is that a huge asteroid hit Earth about 66 million years ago. The impact changed the climate and made survival difficult for many species.",
    category: "Science",
    tags: ["dinosaurs", "history", "science"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why are bees important?",
    answer: "Bees are important because they pollinate many plants. Pollination helps fruits, vegetables, and flowers reproduce.",
    category: "Science",
    tags: ["bees", "nature", "pollination"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why do plants need sunlight?",
    answer: "Plants need sunlight for photosynthesis. They use light to turn water and carbon dioxide into energy-rich sugar.",
    category: "Science",
    tags: ["plants", "sunlight", "photosynthesis"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is the difference between weather and climate?",
    answer: "Weather describes short-term conditions like today's temperature or rain. Climate describes long-term patterns over many years.",
    category: "Science",
    tags: ["weather", "climate", "earth"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Why should you drink water?",
    answer: "You need water to regulate body temperature, transport nutrients, support digestion, and keep organs working properly.",
    category: "Medical",
    tags: ["water", "health", "hydration"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "How many hours of sleep do adults need?",
    answer: "Most adults need about 7 to 9 hours of sleep per night. The exact amount varies by age, health, and lifestyle.",
    category: "Medical",
    tags: ["sleep", "health", "wellness"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "Why is sleep important?",
    answer: "Sleep helps the body recover and supports memory, mood, concentration, and the immune system.",
    category: "Medical",
    tags: ["sleep", "memory", "health"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "Why is exercise good for your health?",
    answer: "Exercise supports the heart, muscles, sleep, and mood. Regular movement can also reduce stress and help prevent some diseases.",
    category: "Medical",
    tags: ["exercise", "health", "wellness"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "What is the difference between a virus and a bacterium?",
    answer: "A bacterium is a living single-celled organism. A virus is much smaller and needs a host cell to reproduce. Antibiotics can work on some bacteria, but not on viruses.",
    category: "Medical",
    tags: ["virus", "bacteria", "health"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "Why do people get a fever?",
    answer: "A fever is the body's response to infection or inflammation. It can help the immune system fight certain germs.",
    category: "Medical",
    tags: ["fever", "health", "infection"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "Why does stress make you tired?",
    answer: "Stress keeps the body in an alert state. Over time, that extra effort can drain energy and make you feel tired.",
    category: "Medical",
    tags: ["stress", "fatigue", "health"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "How can I sleep better naturally?",
    answer: "Keep a regular schedule, reduce screens before bed, avoid caffeine late in the day, and keep your room cool, dark, and quiet.",
    category: "Medical",
    tags: ["sleep", "habits", "wellness"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "Why are vitamins important?",
    answer: "Vitamins help the body function properly. They support energy, immunity, growth, bones, skin, and many internal processes.",
    category: "Medical",
    tags: ["vitamins", "nutrition", "health"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "Why is washing your hands important?",
    answer: "Washing your hands reduces the spread of germs. It is one of the simplest ways to lower the risk of some infections.",
    category: "Medical",
    tags: ["hygiene", "health", "germs"],
    user: "med@seed.echoai.dev",
  },
  {
    prompt: "How do I make a simple budget?",
    answer: "List your income, fixed costs, variable costs, and savings goals. A simple starting point is 50% needs, 30% wants, and 20% savings or debt repayment.",
    category: "Finance",
    tags: ["budget", "money", "personal-finance"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "What is inflation?",
    answer: "Inflation means prices rise over time. When inflation happens, the same amount of money buys less than before.",
    category: "Finance",
    tags: ["inflation", "economics", "money"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "What is saving money?",
    answer: "Saving money means setting money aside instead of spending it immediately. Savings can help with emergencies, future goals, or investments.",
    category: "Finance",
    tags: ["saving", "money", "personal-finance"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "What is the difference between gross salary and net salary?",
    answer: "Gross salary is the amount before deductions. Net salary is what you actually receive after taxes and contributions.",
    category: "Finance",
    tags: ["salary", "work", "money"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "What is compound interest?",
    answer: "Compound interest means earning interest on both the original amount and the interest already earned. That is why money can grow faster over time.",
    category: "Finance",
    tags: ["interest", "saving", "investing"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "What is a stock?",
    answer: "A stock is a small ownership share in a company. Its value can rise or fall depending on the company and the market.",
    category: "Finance",
    tags: ["stocks", "investing", "market"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "What is an ETF?",
    answer: "An ETF is a fund traded on a stock exchange. It usually holds a basket of assets, which can make investing more diversified.",
    category: "Finance",
    tags: ["etf", "stocks", "investing"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "Why should you diversify investments?",
    answer: "Diversification means not putting all your money in one place. It can reduce risk because losses in one area may be balanced by gains elsewhere.",
    category: "Finance",
    tags: ["diversification", "investing", "risk"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "What is a loan?",
    answer: "A loan is money you borrow and agree to repay later, usually with interest.",
    category: "Finance",
    tags: ["loan", "credit", "money"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "How can I save money easily?",
    answer: "Track your spending, cancel unused subscriptions, compare prices, and set up automatic savings each month.",
    category: "Finance",
    tags: ["saving", "money", "budget"],
    user: "finance@seed.echoai.dev",
  },
  {
    prompt: "How do I write a professional email?",
    answer: "Use a clear subject line, a polite greeting, a short explanation, a specific request, and a simple closing.",
    category: "Writing",
    tags: ["email", "work", "communication"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I politely ask for a reply?",
    answer: "You can write: Hi, I wanted to follow up on my previous message. Have you had a chance to review it? Please let me know if you need anything from me.",
    category: "Writing",
    tags: ["email", "follow-up", "polite"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I say no politely?",
    answer: "Thank the person, give a clear answer, and offer an alternative if possible. For example: Thank you for thinking of me, but I cannot commit to this right now.",
    category: "Writing",
    tags: ["communication", "politeness", "work"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I start a cover letter?",
    answer: "Start by naming the role, explaining why it interests you, and showing what you can bring. Avoid generic openings.",
    category: "Writing",
    tags: ["cover-letter", "jobs", "career"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How should I answer 'tell me about yourself'?",
    answer: "Use a simple structure: what you do now, relevant past experience, and why this opportunity interests you. Keep it around one minute.",
    category: "Writing",
    tags: ["interview", "jobs", "career"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I summarize a text?",
    answer: "Read the text, identify the main idea, note the key points, and rewrite them in your own words without unnecessary details.",
    category: "Writing",
    tags: ["summary", "writing", "study"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How can I improve my spelling?",
    answer: "Read regularly, review your mistakes, write often, and use spell checkers as learning tools rather than relying on them completely.",
    category: "Writing",
    tags: ["spelling", "writing", "language"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I write a thank-you message?",
    answer: "Keep it simple and sincere. Say thank you, mention what you appreciated, and end with a warm closing.",
    category: "Writing",
    tags: ["thanks", "message", "communication"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I write an essay introduction?",
    answer: "An essay introduction usually includes a hook, the topic, the main question, and a brief outline of the structure.",
    category: "Writing",
    tags: ["essay", "study", "writing"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I find a good title?",
    answer: "A good title is clear, specific, and interesting. It should quickly tell the reader what the content is about.",
    category: "Writing",
    tags: ["title", "writing", "content"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I calculate a percentage?",
    answer: "Divide the part by the whole, then multiply by 100. For example, 25 out of 50 is 25 / 50 x 100 = 50%.",
    category: "Math",
    tags: ["percentage", "calculation", "math"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "How do I calculate an average?",
    answer: "Add all the values, then divide by how many values there are. For example, 10, 12, and 14 give 36 / 3 = 12.",
    category: "Math",
    tags: ["average", "calculation", "math"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is a fraction?",
    answer: "A fraction represents part of a whole. For example, 1/2 means one part out of two equal parts.",
    category: "Math",
    tags: ["fraction", "math", "basics"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is a prime number?",
    answer: "A prime number is a whole number greater than 1 that can only be divided by 1 and itself. Examples include 2, 3, 5, 7, and 11.",
    category: "Math",
    tags: ["prime-number", "math", "arithmetic"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "How do I convert kilometers to meters?",
    answer: "Multiply kilometers by 1,000. For example, 3 kilometers equals 3,000 meters.",
    category: "Math",
    tags: ["conversion", "meters", "math"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "How do I convert hours to minutes?",
    answer: "Multiply hours by 60. For example, 2 hours equals 120 minutes.",
    category: "Math",
    tags: ["conversion", "time", "math"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is the Pythagorean theorem?",
    answer: "The Pythagorean theorem says that in a right triangle, a squared plus b squared equals c squared, where c is the longest side.",
    category: "Math",
    tags: ["pythagorean-theorem", "geometry", "math"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "How do I solve a simple equation?",
    answer: "The goal is to isolate the unknown value. Do the same operation on both sides so the equation stays balanced.",
    category: "Math",
    tags: ["equation", "algebra", "math"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "What is a right angle?",
    answer: "A right angle measures 90 degrees. It is the kind of angle found in the corner of a square or rectangle.",
    category: "Math",
    tags: ["angle", "geometry", "math"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "How do I calculate the area of a rectangle?",
    answer: "Multiply the length by the width. For example, a rectangle that is 5 by 3 has an area of 15 square units.",
    category: "Math",
    tags: ["area", "rectangle", "math"],
    user: "science@seed.echoai.dev",
  },
  {
    prompt: "Who was Napoleon Bonaparte?",
    answer: "Napoleon Bonaparte was a French general and emperor who ruled France in the early 19th century and reshaped much of European history.",
    category: "History",
    tags: ["napoleon", "france", "history"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "Why did the French Revolution start?",
    answer: "The French Revolution began because of inequality, financial crisis, rising food prices, and growing opposition to absolute monarchy.",
    category: "History",
    tags: ["french-revolution", "france", "history"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "What was the Renaissance?",
    answer: "The Renaissance was a period of renewed art, science, and culture in Europe. It revived interest in ancient Greek and Roman ideas.",
    category: "History",
    tags: ["renaissance", "europe", "history"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "Who discovered America?",
    answer: "Christopher Columbus reached the Americas in 1492 from a European perspective, but the continent was already inhabited by Indigenous peoples for thousands of years.",
    category: "History",
    tags: ["america", "columbus", "history"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "Why did World War 1 start?",
    answer: "World War 1 started after the assassination of Archduke Franz Ferdinand in 1914, but deeper causes included alliances, nationalism, imperial rivalry, and militarization.",
    category: "History",
    tags: ["world-war-1", "history", "europe"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "Why did World War 2 start?",
    answer: "World War 2 began in 1939 when Nazi Germany invaded Poland. The causes also included the Treaty of Versailles, economic crisis, and the rise of totalitarian regimes.",
    category: "History",
    tags: ["world-war-2", "history", "europe"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "Who was Julius Caesar?",
    answer: "Julius Caesar was a Roman general and politician who played a major role in the fall of the Roman Republic. He was assassinated in 44 BC.",
    category: "History",
    tags: ["rome", "caesar", "history"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "What was ancient Egypt?",
    answer: "Ancient Egypt was a civilization along the Nile River, known for pharaohs, pyramids, temples, hieroglyphs, and major architectural achievements.",
    category: "History",
    tags: ["egypt", "ancient-history", "history"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "Who were the Vikings?",
    answer: "The Vikings were Scandinavian peoples active mainly from the 8th to the 11th century. They were sailors, traders, explorers, and sometimes raiders.",
    category: "History",
    tags: ["vikings", "scandinavia", "history"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "What was the Cold War?",
    answer: "The Cold War was a period of tension between the United States and the Soviet Union after World War 2. It was called cold because they did not fight each other directly in a full war.",
    category: "History",
    tags: ["cold-war", "history", "politics"],
    user: "history@seed.echoai.dev",
  },
  {
    prompt: "What is a contract?",
    answer: "A contract is an agreement between two or more parties that creates obligations. It can be written or sometimes oral, but written contracts are easier to prove.",
    category: "Legal",
    tags: ["contract", "law", "agreement"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What is an invoice?",
    answer: "An invoice is a document that lists goods or services provided, the price, taxes if applicable, the date, and the seller and customer details.",
    category: "Legal",
    tags: ["invoice", "admin", "business"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What is insurance?",
    answer: "Insurance is a contract that protects against certain risks. In exchange for payments, the insurer may compensate you if a covered problem occurs.",
    category: "Legal",
    tags: ["insurance", "contract", "admin"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What is the difference between copyright and trademark?",
    answer: "Copyright protects creative works like texts, music, images, and code. A trademark protects brand identifiers like names, logos, and slogans.",
    category: "Legal",
    tags: ["copyright", "trademark", "intellectual-property"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What is a formal notice?",
    answer: "A formal notice is an official letter asking someone to fulfill an obligation, such as paying a debt or respecting a contract, before further action is taken.",
    category: "Legal",
    tags: ["formal-notice", "law", "admin"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What is a lease?",
    answer: "A lease is a rental contract between a landlord and a tenant. It sets the property, rent, duration, obligations, and rental conditions.",
    category: "Legal",
    tags: ["lease", "housing", "contract"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What is a power of attorney?",
    answer: "A power of attorney is a document that lets one person act on behalf of another for specific tasks, such as signing or collecting documents.",
    category: "Legal",
    tags: ["power-of-attorney", "admin", "law"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What is a quote or estimate?",
    answer: "A quote or estimate is a proposed price for a product or service. It usually describes what will be provided and the expected cost.",
    category: "Legal",
    tags: ["quote", "business", "admin"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What is an NDA?",
    answer: "An NDA, or non-disclosure agreement, is a contract that requires one or more people to keep certain information confidential.",
    category: "Legal",
    tags: ["nda", "confidentiality", "contract"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "What should I do after a car accident?",
    answer: "Check for injuries, call emergency services if needed, move to safety, take photos, exchange information, and contact your insurance company.",
    category: "Legal",
    tags: ["car-accident", "insurance", "car"],
    user: "legal@seed.echoai.dev",
  },
  {
    prompt: "How do I stop procrastinating?",
    answer: "Make the task smaller and easier to start. Instead of planning to finish everything, begin with one tiny action, such as opening the document.",
    category: "General",
    tags: ["procrastination", "productivity", "habits"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I manage my time better?",
    answer: "Write down your priorities, block time for important work, and reduce distractions. A short list of three daily priorities is often more useful than a long list.",
    category: "General",
    tags: ["time", "organization", "productivity"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How can I learn faster?",
    answer: "Use active recall, practice often, explain ideas in your own words, and review over time. Practice usually beats passive reading.",
    category: "General",
    tags: ["learning", "memory", "study"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I stay motivated?",
    answer: "Connect your goal to a clear reason, break it into small steps, and track progress. Habits are more reliable than waiting for motivation.",
    category: "General",
    tags: ["motivation", "habits", "goals"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I make a good decision?",
    answer: "Clarify the problem, list options, compare benefits and risks, then choose with the information you have. Waiting for perfect certainty can block action.",
    category: "General",
    tags: ["decision", "thinking", "organization"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I make an effective to-do list?",
    answer: "Write actions, not vague ideas. For example, use 'email the client' instead of 'client project'. Keep the list short enough to be realistic.",
    category: "General",
    tags: ["organization", "todo", "productivity"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How can I improve my focus?",
    answer: "Work in short blocks, remove distractions, turn off notifications, and take regular breaks. A simple environment makes focus easier.",
    category: "General",
    tags: ["focus", "concentration", "productivity"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I introduce myself simply?",
    answer: "Say your name, what you do, your main experience, and what you are looking for or offering. Keep it clear and natural.",
    category: "General",
    tags: ["introduction", "communication", "work"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I make friends?",
    answer: "Create regular chances to see the same people, ask sincere questions, suggest simple activities, and let the relationship grow over time.",
    category: "General",
    tags: ["friends", "relationships", "daily-life"],
    user: "career@seed.echoai.dev",
  },
  {
    prompt: "How do I handle an argument calmly?",
    answer: "Slow down, listen before replying, describe facts instead of attacking the person, and focus on one specific issue to solve.",
    category: "General",
    tags: ["conflict", "communication", "relationships"],
    user: "career@seed.echoai.dev",
  },
];

export const GPT55_SIMPLE_ANSWERS: Gpt55SimpleAnswer[] = GPT55_SIMPLE_ANSWER_SUMMARIES.map((item) => ({
  ...item,
  answer: chatGptStyleAnswer(item.prompt, item.answer, item.category),
}));
