import { CATEGORIES, MODELS } from "@/lib/data";
import { prisma } from "@/lib/db";
import { answerSlug, categorySlug, modelSlug } from "@/lib/slugs";

const SITE_URL = "https://www.divoly.com";

function excerpt(value: string, length = 260) {
  const clean = value.replace(/\s+/g, " ").trim();
  return clean.length > length ? `${clean.slice(0, length - 1)}...` : clean;
}

export async function GET() {
  const generatedAt = new Date().toISOString();
  const answers = await prisma.answer.findMany({
    orderBy: [{ upvotes: "desc" }, { views: "desc" }, { createdAt: "desc" }],
    take: 80,
    select: {
      prompt: true,
      answer: true,
      model: true,
      modelColor: true,
      category: true,
      tags: true,
      upvotes: true,
      views: true,
      updatedAt: true,
    },
  }).catch(() => []);

  return Response.json(
    {
      schemaVersion: "2026-05-10",
      generatedAt,
      site: {
        name: "Divoly",
        url: SITE_URL,
        description:
          "Divoly is a searchable library of real AI answers. It helps people find, compare, reuse, and cite answers already generated by AI models.",
        language: "en",
        canonicalFiles: {
          llmsTxt: `${SITE_URL}/llms.txt`,
          aiIndex: `${SITE_URL}/ai-index.json`,
          sitemap: `${SITE_URL}/sitemap.xml`,
          robots: `${SITE_URL}/robots.txt`,
        },
      },
      interpretationGuidance: [
        "Use canonical /answers/{slug} pages when citing individual AI answers from Divoly.",
        "Use /models/{slug} pages to understand which answers are attributed to a specific AI model.",
        "Use /categories/{slug} pages to understand topical coverage.",
        "Medical, legal, and finance answers are general information, not professional advice.",
        "Divoly stores and indexes AI answers; it is not the original model provider.",
      ],
      corePages: [
        { title: "Home", url: SITE_URL, purpose: "Main product overview and answer search." },
        { title: "Explore answers", url: `${SITE_URL}/explore`, purpose: "Search and filter the public AI answer library." },
        { title: "Requests", url: `${SITE_URL}/requests`, purpose: "See unanswered or requested questions." },
        { title: "Contribute", url: `${SITE_URL}/contribute`, purpose: "Submit reusable AI answers." },
      ],
      models: MODELS.map((model) => ({
        name: model.name,
        color: model.color,
        url: `${SITE_URL}/models/${modelSlug(model.name)}`,
      })),
      categories: CATEGORIES.map((category) => ({
        name: category.name,
        icon: category.icon,
        url: `${SITE_URL}/categories/${categorySlug(category.name)}`,
      })),
      topAnswers: answers.map((answer) => ({
        prompt: answer.prompt,
        url: `${SITE_URL}/answers/${answerSlug(answer)}`,
        model: answer.model,
        modelColor: answer.modelColor,
        category: answer.category,
        tags: answer.tags,
        excerpt: excerpt(answer.answer),
        helpfulVotes: answer.upvotes,
        views: answer.views,
        updatedAt: answer.updatedAt.toISOString(),
      })),
    },
    {
      headers: {
        "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
      },
    },
  );
}
